import { StyleSheet } from 'react-native';

import {
  AppColors,
  AppRadii,
  AppSpacing,
  layoutPrimitives,
  surfacePrimitives,
  textPrimitives,
} from '@/styles';

export const styles = StyleSheet.create({
  safeArea: layoutPrimitives.screen,
  header: {
    ...layoutPrimitives.headerRow,
    alignItems: 'center',
    paddingHorizontal: AppSpacing.screen,
    paddingTop: AppSpacing.md,
    paddingBottom: AppSpacing.md,
  },
  backBtn: surfacePrimitives.iconButton,
  headerLabel: {
    fontSize: 17,
    fontWeight: '700',
    color: AppColors.text,
  },
  headerGhost: {
    width: 40,
    height: 40,
  },
  scrollContent: {
    padding: AppSpacing.screen,
    paddingBottom: AppSpacing.bottom,
    gap: AppSpacing.xxl,
  },
  heroCard: {
    backgroundColor: AppColors.text,
    borderRadius: AppRadii.hero,
    padding: AppSpacing.screen,
  },
  heroTopRow: {
    ...layoutPrimitives.headerRow,
    alignItems: 'center',
    marginBottom: AppSpacing.section,
  },
  heroBadge: {
    ...layoutPrimitives.centerRow,
    backgroundColor: AppColors.surfaceAccent,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: AppRadii.full,
    gap: AppSpacing.xs,
  },
  heroBadgeText: {
    ...textPrimitives.captionStrong,
    color: AppColors.primary,
  },
  liveChip: {
    ...layoutPrimitives.centerRow,
    gap: AppSpacing.xs,
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: AppRadii.full,
    backgroundColor: AppColors.success,
  },
  plcDot: {
    backgroundColor: AppColors.success,
  },
  dashboardDot: {
    backgroundColor: AppColors.primary,
  },
  liveChipText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#D5D9D5',
  },
  heroTitle: {
    color: AppColors.textInverse,
    fontSize: 24,
    fontWeight: '800',
    lineHeight: 31,
    marginBottom: AppSpacing.md,
  },
  heroSubtitle: {
    fontSize: 14,
    lineHeight: 21,
    color: AppColors.textInverseSubtle,
  },
  sectionCard: {
    backgroundColor: AppColors.surface,
    borderRadius: AppRadii.xxl,
    padding: AppSpacing.section,
  },
  sectionHeaderRow: {
    ...layoutPrimitives.headerRow,
    alignItems: 'center',
    gap: AppSpacing.md,
    marginBottom: AppSpacing.md,
  },
  sectionTitle: textPrimitives.sectionTitle,
  sectionBadge: {
    ...layoutPrimitives.centerRow,
    width: 28,
    height: 28,
    borderRadius: AppRadii.full,
    backgroundColor: AppColors.backgroundMuted,
  },
  inlineDot: {
    width: 8,
    height: 8,
    borderRadius: AppRadii.full,
  },
  sectionDescription: {
    ...textPrimitives.body,
    marginBottom: AppSpacing.xl,
  },
  fieldBlock: {
    marginBottom: AppSpacing.xl,
  },
  fieldHeaderRow: {
    ...layoutPrimitives.headerRow,
    alignItems: 'center',
    gap: AppSpacing.lg,
    marginBottom: AppSpacing.sm,
  },
  fieldLabel: textPrimitives.label,
  input: {
    ...surfacePrimitives.textInput,
    borderWidth: 1,
    borderColor: AppColors.border,
  },
  pressureValue: {
    fontSize: 14,
    fontWeight: '800',
    color: AppColors.text,
  },
  pressureValueDanger: {
    color: AppColors.error,
  },
  pressureSlider: {
    height: 42,
  },
  sliderRangeRow: {
    ...layoutPrimitives.centerRow,
    justifyContent: 'space-between',
    gap: AppSpacing.sm,
    marginTop: AppSpacing.xs,
  },
  sliderRangeText: {
    fontSize: 12,
    fontWeight: '700',
    color: AppColors.textSubtle,
  },
  pressureLimitBadge: {
    paddingHorizontal: AppSpacing.md,
    paddingVertical: AppSpacing.xxs,
    borderRadius: AppRadii.full,
    backgroundColor: AppColors.surfaceMuted,
  },
  pressureLimitBadgeDanger: {
    backgroundColor: AppColors.surfaceError,
  },
  pressureLimitText: {
    fontSize: 11,
    fontWeight: '800',
    color: AppColors.textMuted,
  },
  pressureLimitTextDanger: {
    color: AppColors.error,
  },
  stepperButtonDisabled: {
    opacity: 0.45,
  },
  dashboardFieldBlock: {
    marginBottom: AppSpacing.xl,
  },
  dashboardControlCard: {
    backgroundColor: AppColors.surface,
    borderRadius: AppRadii.lg,
    borderWidth: 1,
    borderColor: '#F5D3C5',
    padding: AppSpacing.xl,
    shadowColor: '#000000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 1,
  },
  dashboardControlHeader: {
    ...layoutPrimitives.headerRow,
    alignItems: 'center',
    gap: AppSpacing.md,
    marginBottom: AppSpacing.md,
  },
  dashboardValueChip: {
    paddingHorizontal: AppSpacing.md,
    paddingVertical: AppSpacing.xs,
    borderRadius: AppRadii.full,
    backgroundColor: AppColors.surfaceAccent,
  },
  dashboardValueChipStable: {
    backgroundColor: AppColors.surfaceSuccess,
  },
  dashboardValueChipWarning: {
    backgroundColor: '#FFF4DB',
  },
  dashboardValueChipDanger: {
    backgroundColor: AppColors.surfaceError,
  },
  dashboardValueChipText: {
    fontSize: 11,
    fontWeight: '800',
    color: AppColors.primary,
  },
  dashboardValueChipTextStable: {
    color: AppColors.success,
  },
  dashboardValueChipTextWarning: {
    color: '#B7791F',
  },
  dashboardValueChipTextDanger: {
    color: AppColors.error,
  },
  dashboardControlHint: {
    marginTop: AppSpacing.md,
    fontSize: 12,
    lineHeight: 17,
    color: AppColors.textSubtle,
  },
  dashboardToggleRow: {
    ...layoutPrimitives.centerRow,
    justifyContent: 'space-between',
    minHeight: 52,
    gap: AppSpacing.lg,
  },
  dashboardToggleValue: {
    marginTop: AppSpacing.xs,
    fontSize: 16,
    fontWeight: '800',
    color: AppColors.text,
  },
  alarmToggle: {
    position: 'relative',
    width: 118,
    height: 46,
    borderRadius: AppRadii.full,
    padding: 4,
    borderWidth: 1,
    justifyContent: 'center',
  },
  alarmToggleInactive: {
    backgroundColor: AppColors.surfaceMuted,
    borderColor: AppColors.border,
  },
  alarmToggleActive: {
    backgroundColor: AppColors.surfaceError,
    borderColor: '#F8B4B4',
  },
  alarmToggleTrack: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: AppSpacing.md,
  },
  alarmToggleLabel: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.6,
    color: AppColors.textSubtle,
  },
  alarmToggleLabelActive: {
    color: AppColors.text,
  },
  alarmToggleThumb: {
    position: 'absolute',
    top: 4,
    width: 52,
    height: 36,
    borderRadius: AppRadii.full,
    backgroundColor: AppColors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  alarmToggleThumbInactive: {
    left: 4,
  },
  alarmToggleThumbActive: {
    left: 62,
  },
  dashboardStepperRow: {
    ...layoutPrimitives.centerRow,
    gap: AppSpacing.sm,
  },
  dashboardStepperButton: {
    width: 48,
    height: 56,
    borderRadius: AppRadii.md,
    backgroundColor: AppColors.surfaceMuted,
    borderWidth: 1,
    borderColor: AppColors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dashboardReadoutShell: {
    ...layoutPrimitives.centerRow,
    flex: 1,
    minHeight: 56,
    borderRadius: AppRadii.md,
    backgroundColor: '#FFF8F4',
    borderWidth: 1,
    borderColor: '#F5D3C5',
    paddingLeft: AppSpacing.xxl,
    paddingRight: AppSpacing.xl,
  },
  dashboardReadoutInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 0,
    fontSize: 18,
    fontWeight: '800',
    color: AppColors.text,
  },
  dashboardReadoutUnit: {
    fontSize: 13,
    fontWeight: '800',
    color: AppColors.primary,
  },
  statusSegmentRow: {
    flexDirection: 'row',
    gap: AppSpacing.sm,
    marginTop: AppSpacing.sm,
  },
  statusSegmentButton: {
    flex: 1,
    minHeight: 110,
    borderRadius: AppRadii.lg,
    backgroundColor: AppColors.surface,
    borderWidth: 1,
    borderColor: AppColors.border,
    paddingHorizontal: AppSpacing.md,
    paddingVertical: AppSpacing.md,
  },
  statusSegmentButtonActive: {
    shadowColor: '#000000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  statusSegmentTopRow: {
    ...layoutPrimitives.headerRow,
    alignItems: 'center',
    marginBottom: AppSpacing.md,
  },
  statusSegmentLamp: {
    width: 10,
    height: 10,
    borderRadius: AppRadii.full,
    opacity: 0.45,
  },
  statusSegmentLampActive: {
    opacity: 1,
  },
  statusSegmentCode: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.5,
    color: AppColors.textSubtle,
  },
  statusSegmentCap: {
    width: 48,
    height: 48,
    borderRadius: AppRadii.full,
    backgroundColor: AppColors.surfaceMuted,
    borderWidth: 1,
    borderColor: AppColors.border,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: AppSpacing.md,
  },
  statusSegmentCapActive: {
    backgroundColor: AppColors.surface,
  },
  statusSegmentText: {
    fontSize: 12,
    fontWeight: '800',
    color: AppColors.text,
    textAlign: 'center',
  },
  statusSegmentTextActive: {
    color: AppColors.text,
  },
  dashboardPressureSlider: {
    height: 42,
  },
  dashboardInputShell: {
    ...layoutPrimitives.centerRow,
    minHeight: 52,
    borderRadius: AppRadii.md,
    backgroundColor: AppColors.surface,
    borderWidth: 1,
    borderColor: AppColors.border,
    paddingLeft: AppSpacing.xxl,
    paddingRight: AppSpacing.xl,
    marginTop: AppSpacing.sm,
  },
  dashboardNumberInput: {
    flex: 1,
    minWidth: 0,
    paddingVertical: 0,
    fontSize: 16,
    fontWeight: '800',
    color: AppColors.text,
  },
  dashboardUnitText: {
    fontSize: 13,
    fontWeight: '700',
    color: AppColors.textSubtle,
  },
  summaryCard: {
    backgroundColor: AppColors.surfaceAccent,
    borderRadius: AppRadii.xxl,
    padding: AppSpacing.section,
  },
  summaryTitle: textPrimitives.sectionTitle,
  summaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: AppSpacing.lg,
  },
  summaryItem: {
    width: '47%',
    backgroundColor: AppColors.surface,
    borderRadius: AppRadii.lg,
    padding: AppSpacing.xl,
  },
  summaryLabel: {
    ...textPrimitives.label,
    marginBottom: AppSpacing.xs,
  },
  summaryValue: {
    fontSize: 18,
    fontWeight: '800',
    color: AppColors.text,
  },
  statusCard: {
    ...layoutPrimitives.centerRow,
    backgroundColor: AppColors.surface,
    borderRadius: AppRadii.md,
    paddingHorizontal: AppSpacing.xl,
    paddingVertical: AppSpacing.lg,
    gap: AppSpacing.md,
  },
  statusText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 18,
    color: AppColors.textMuted,
  },
  primaryButton: {
    backgroundColor: AppColors.primary,
    borderRadius: AppRadii.hero,
    paddingVertical: AppSpacing.section,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: AppColors.textInverse,
    fontSize: 16,
    fontWeight: '700',
  },
  bottomSpacer: {
    height: 96,
  },
});
